# Generated by Django 5.2.4 on 2025-07-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_initial'),
        ('users', '0003_userfollowing_customuser_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='muted_communities',
            field=models.ManyToManyField(blank=True, related_name='muted_by_profiles', to='communities.community'),
        ),
    ]
