# Generated by Django 5.2.4 on 2025-07-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_initial'),
        ('users', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notified_communities',
            field=models.ManyToManyField(blank=True, related_name='notified_profiles', to='communities.community'),
        ),
    ]
